name: Beyonders Release
description:
  Action to create a new Release and github and update all the details in Notion
  accordingly.
author: Beyonders Digital Solutions

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: aperture
  color: green

# Define your inputs here.
inputs:
  project:
    description: Name of the project
    required: true
    default: lup
  repo-category:
    description: Stack Category of the project (like Web, Backend, etc)
    required: true
    default: Backend

# Define your outputs here.
outputs:
  new-version:
    description: The new version of the project

runs:
  using: node20
  main: dist/index.js
